### PR TITLE
Created CODE_OF_CONDUCT.md  #16

### PR DESCRIPTION
**Pull request by Nelcy17**
image

image

### CODE REVIEW

**Comment by kvcops** [comment]
It's nice...but please try to decrease the information smaller and in the form of key points with better formatting

**Comment by kvcops** [comment]
Please include the complete features and functionalities ok kv nexus

**Comment by Nelcy17** [comment]
> Please include the complete features and functionalities of kv nexus

Can you suggest more features or should I add the features which were there before updating.

**Comment by kvcops** [comment]
These are the complete features that kv nexus offers...include them in the md file

**Comment by Nelcy17** [comment]
> 
> 
> These are the complete features that kv nexus offers...include them in the md file

Done!
image
kindly  label it as gssoc ext and also add the levels.

**Comment by ShashwatAgrawal20** [comment]
closes #16

**Pull request merged**
