### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Nelcy17**
Added the Star Rating Functionality above the Contact Us Section.

image

image

### CODE REVIEW

**Comment by kvcops** [comment]
can you link the review system to the firebase database to store it up...

**Comment by Nelcy17** [comment]
> can you link the review system to the firebase database to store it up...

Can I add this as a new issue?

**Comment by kvcops** [comment]
Yep...just make sure to use the present code to store the review system along with the login credentials...

**Comment by kvcops** [comment]
If you are having issues to add this feature or to append to firebase database just inform me...I'll implement it

**Comment by Nelcy17** [comment]
> Yep...just make sure to use the present code to store the review system along with the login credentials..

Okayy

I have also added the MIT LICENCE and security.md file you can check that too in the commits.

Can you assign me labels in this PR?

**Pull request merged**
