### PR TITLE
Revert "Restrict Contact Us Email Domain Validation"

### PR DESCRIPTION
**Pull request by kvcops**
Reverts kvcops/KV-Nexus#37

### CODE REVIEW

**Comment by smog-root** [comment]
Add labels!!! And assign me!!

**Comment by smog-root** [comment]
@techy4shri Add labels and assign me!!

**Comment by smog-root** [comment]
@kvcops ???? Add labels??? And assign me!!!

**Comment by kvcops** [comment]
Have you fixed the css issue in the contact us form (i.e the labels are out of the input boxes...have you checked it?)

**Comment by smog-root** [comment]
Why did you decreased the level?? It's level2 on the issue!! Kindly make it level2!!

**Comment by smog-root** [comment]
> Have you fixed the css issue in the contact us form (i.e the labels are out of the input boxes...have you checked it?)

Yes I have checked it.. I don't have access to commit to this PR now.. because of revert and merge!! I will make another PR with changes!!

I don't need any labels for that one!!

**Comment by techy4shri** [comment]
@smog-root refrain from using exclaimation, this is a revert PR, not the PR you raised.

**Pull request merged**
