### PR TITLE
Update chat.html

### PR DESCRIPTION
**Pull request by EvanSingee**
Tried to fix bugs & added ui changes

### CODE REVIEW

**Comment by EvanSingee** [comment]
@kvcops

**Comment by kvcops** [comment]
it's still washed out and still seems outdated...

This is the ui that you have suggested : 

Screenshot 2024-10-28 085849


this is the previous UI:

image

**Comment by kvcops** [comment]
It seems like for every PR it's been outdated...just try to work it on .... i am still hoping for the chance for the improvements

**Comment by kvcops** [comment]
be waiting for your next PR :)

**Pull request closed without merging**
