### PR TITLE
ADDED THE FEATURE OF TRANSLATION

### LINKED ISSUE #30: Add language Translator so that more user can read and use this website
image
I can work in this

### PR DESCRIPTION
**Pull request by HimangshuSharma01**
Added  the translator to the necessary outputs.... 

closes #30 
 
image
Screenshot 2024-10-26 153313
Screenshot 2024-10-26 153305

### CODE REVIEW

**Comment by kvcops** [comment]
there is no need for translating option for the flowchart ...only add it for the health , chat ,chef , story and psychology prediction

**Comment by HimangshuSharma01** [comment]
@kvcops ok sir doing it

**Comment by HimangshuSharma01** [comment]
image
Added it to the health paqe and removed from the flowchart page Please give level 3

**Comment by kvcops** [comment]
btw...have you modified the containers for translate for the mobile layout too (the resonsiveness)..?

**Comment by HimangshuSharma01** [comment]
https://github.com/user-attachments/assets/e06aec1c-f347-42eb-af93-113835074ece

**Comment by kvcops** [comment]
Yep...this seems nice 🙂

**Comment by kvcops** [comment]
Can you send me the pr again?

**Comment by HimangshuSharma01** [comment]
> Can you send me the pr again?

There is no option for another pull request I need to close this one in order to raise one more

**Comment by kvcops** [comment]
Ok ..do you need any help on it ?

**Comment by HimangshuSharma01** [comment]
> Ok ..do you need any help on it ?
No it's fine I can manage..

**Pull request closed without merging**
