### PR TITLE
fixed the bug and added the feature

### PR DESCRIPTION
**Pull request by HimangshuSharma01**
Fixed the bug and Added a good translator button also the overflow will not happen

### CODE REVIEW

**Comment by HimangshuSharma01** [comment]
@kvcops hope you like this

**Comment by kvcops** [comment]
Let me merge this and check it out

**Comment by kvcops** [comment]
There is this issue in the mobile layout. ..

The buttons overlapped with each other

**Comment by HimangshuSharma01** [comment]
> There is this issue in the mobile layout. ..
> 
> The buttons overlapped with each other

Fixed it

**Comment by HimangshuSharma01** [comment]
@kvcops please add labels

**Pull request merged**
