### PR TITLE
To adding animation effect on social media icons 

### LINKED ISSUE #8: To adding the animation effect to social media icons in the footer page
### screenshot

image

### PR DESCRIPTION
**Pull request by Sujal1201**
## Issue: animation effect on social media icons

**before**

image

**after**

https://github.com/user-attachments/assets/79c3c177-d2c7-4983-9b65-be3510e355e5

closes #8

### CODE REVIEW

**Comment by Sujal1201** [comment]
please give me a level 2 badge

**Comment by Sujal1201** [comment]
Okay I check the problem

**Comment by kvcops** [comment]
Ok...will be waiting for the changes to complete

**Review by kvcops — APPROVED** [review]

**Comment by kvcops** [comment]
it seems the footer is still a lot more width...kindly fix it ..

**Pull request merged**
