### PR TITLE
Revert "Update chat.html"

### PR DESCRIPTION
**Pull request by kvcops**
Reverts kvcops/KV-Nexus#56

### CODE REVIEW

**Comment by EvanSingee** [comment]
pls assign gssoc level @kvcops

**Comment by EvanSingee** [comment]
any issues? @kvcops 
level-1? wontfix?

**Comment by kvcops** [comment]
I mean it seems outdated also the ui seems washed out...and I haven't observed any improvement along with some bugs in the theme toggle bar...

**Comment by kvcops** [comment]
Please don't get sad about it ..I was hoping that It would be better .. but still you can work it on .. I'll be looking forward to your future updates

**Comment by EvanSingee** [comment]
apologies for the shoddy work.
let me see if next commit might impress you.

**Comment by kvcops** [comment]
be waiting for another PR from your side

**Comment by kvcops** [comment]
@techy4shri  i think its better to close this pr...cause i have changed this html code from external css and js to embedded ...

**Comment by techy4shri** [comment]
@kvcops understood 🫡

**Pull request closed without merging**
