### PR TITLE
Contributors page added

### PR DESCRIPTION
**Pull request by Son7c**
Here is the demo

https://github.com/user-attachments/assets/4f2d7570-73db-419e-b807-6a498bc5ad86

### CODE REVIEW

**Comment by Son7c** [comment]
@kvcops Please merge this PR.

**Comment by kvcops** [comment]
its a contributors page...i think it should look more cool , amazing and visually stunning...can you improve the ui a lot better so that it should look nice and attractive

**Comment by Son7c** [comment]
@kvcops Do you have any suggestions? I'll try to improve it

**Comment by kvcops** [comment]
Make sure it should have visually good animations and cool effects....

**Comment by Son7c** [comment]
@kvcops I'll try my best to add some animations but can you please merge this PR, i'll improve it in a new PR

**Comment by techy4shri** [comment]
@Son7c you need to make the changes in this PR only, the UI needs to align with the rest of the website, do not make any unnecessary changes and you will be good to go.

**Comment by techy4shri** [comment]
@Son7c you only have a few hours to make the suggested changes before I close this PR.

**Pull request closed without merging**
